### PR TITLE
Added Slim-Rails gem

### PR DESCRIPTION
**Pull request by kwals**
Sounds like the class is ok with automatically including the Slim Rails gem. Added it to main Gem list.

### CODE REVIEW

**Comment by jamesdabbs** [comment]
Did you mean to include both commits in this PR? I don't mind pulling the autoloading ask in as well, but using something like [this](http://guides.rubyonrails.org/rails_application_templates.html#environment-application-data-nil-options-block) feels more appropriate.

**Comment by kwals** [comment]
I didn't mean to add both - working on rolling back the second commit...

**Comment by kwals** [comment]
Ok, now it should just be Slim Rails added. Will make the autolib function a separate pull request.

**Comment by jamesdabbs** [comment]
Cool, yeah, I'd definitely like to have that functionality as well. :+1:

**Pull request merged**
